#
# Makefile for Marvell's PXA168 processors line
#

obj-y				+= common.o clock.o devices.o irq.o time.o resource/

# SoC support
obj-$(CONFIG_CPU_PXA168)	+= pxa168.o
obj-$(CONFIG_CPU_PXA910)	+= pxa910.o pxa910-squ.o

# board support
obj-$(CONFIG_MACH_ASPENITE)	+= aspenite.o
obj-$(CONFIG_MACH_ZYLONITE2)	+= aspenite.o
obj-$(CONFIG_MACH_IPCAM)	+= ipcam.o
obj-$(CONFIG_MACH_DKB_GENERIC)	+= dkb_generic.o
obj-$(CONFIG_MACH_AVENGERS_LITE)+= avengers_lite.o
obj-$(CONFIG_MACH_EDGE)		+= edge.o
+obj-$(CONFIG_MACH_WAYLAND)	+= wayland.o
obj-$(CONFIG_MACH_TTC_DKB)	+= ttc_dkb.o
obj-$(CONFIG_MACH_TAVOREVB)	+= tavorevb.o
obj-$(CONFIG_DVFM)		+= dvfm.o
obj-$(CONFIG_DVFM_PXA168)	+= pxa168_dvfm.o pxa168_dfc_ll.o
obj-$(CONFIG_DVFM_PXA910)	+= pxa910_dvfm.o
obj-$(CONFIG_MSPM_PXA168)	+= pxa168_mspm_idle.o pxa168_mspm_prof.o
obj-$(CONFIG_MSPM_PXA910)	+= pxa910_mspm_idle.o pxa910_mspm_prof.o
obj-$(CONFIG_PM_PXA168)		+= pxa168_pm.o pxa168_pm_ll.o
obj-$(CONFIG_PM_PXA910)		+= pxa910_pm.o pxa910_pm_ll.o
obj-$(CONFIG_MMC)		+= mmc.o
